name: 
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - rdkit==2021.03.1
  - pytorch==1.6.0
  - pip>=21.0
  - pip:
    - furo
    - numpy
    - sphinx
    - sphinx_rtd_theme==0.5.2
    - torch-scatter==2.0.6
    - torch-sparse==0.6.9
    - torch-cluster==1.5.9
    - torch-spline-conv==1.2.1
    - torch-geometric==1.7.0
    - git+https://github.com/Chilipp/autodocsumm.git
    - captum==0.2.0
    - cilog
    - typed-argument-parser==1.5.4 
    - tensorboard
