
results_save: False
results_dir: ''
mcts_saved_dir: ''
# mcts_saved_filename: ''
load_results: False
use_gpu: True
explainer_name: 'attn_explainer_tg'
debug_mode: False

param:
  simulate:
    explanation_level: 'event'
    verbose: True
  simulate_v2:
    explanation_level: 'event'
    verbose: True
  garden_5:
    explanation_level: 'event'
    verbose: True
  wikipedia:
    explanation_level: 'event'
    verbose: True

  