
results_save: False
results_dir: ''
mcts_saved_dir: ''
# mcts_saved_filename: ''
load_results: False
use_gpu: True
explainer_name: 'pg_explainer_tg'
explainer_ckpt_dir: ''
debug_mode: False

param:
  simulate:
    explanation_level: 'event'
    verbose: True
    tscore_coef: None
    beta: None
  simulate_v2:
    explanation_level: 'event'
    verbose: True
  garden_5:
    explanation_level: 'event'
    verbose: True
  wikipedia:
    explanation_level: 'event'
    verbose: True
    train_epochs: 10
    reg_coefs:
      - 0.1
      - 0.1
    batch_size: 16
    lr: 1e-4
  reddit:
    explanation_level: 'event'
  


  