explanation_result_dir: ''

param:
  simulate:
    explanation_level: 'event'
    target_event_idx: 9909
    verbose: True
  simulate_v2:
    explanation_level: 'event'
    target_event_idx: 59
    verbose: True

  